### ISSUE TITLE
Problem: Clicking to donate takes user to error page

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#346]
This is in a docker-compose test install.

Clicked to try the $10 donation with a test api key and got a "something went wrong" error on https://ecko.dockerino.local/payment_gateways?package=1

Logs say to set the API key but I did add STRIPE_API_KEY and STRIPE_CALLBACK_URL to `.env.production` then tried restarting the web service, then doing a `docker-compose down` then `docker-compose up -d` to do a full restart of everything.

Here are those logs:
```
web_1        | [58a80b58-eb85-4cea-8e56-4ac627003b7a] method=GET path=/payment_gateways format=html controller=DonationsController action=payment_gateways status=500 error='Stripe::AuthenticationError: No API key provided. Set your API key using "Stripe.api_key = <API-KEY>". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.' duration=22.42 view=0.00 db=7.88
web_1        | [58a80b58-eb85-4cea-8e56-4ac627003b7a]   
web_1        | [58a80b58-eb85-4cea-8e56-4ac627003b7a] Stripe::AuthenticationError (No API key provided. Set your API key using "Stripe.api_key = <API-KEY>". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.):
web_1        | [58a80b58-eb85-4cea-8e56-4ac627003b7a]   
web_1        | [58a80b58-eb85-4cea-8e56-4ac627003b7a] app/controllers/donations_controller.rb:14:in `payment_gateways'
web_1        | [58a80b58-eb85-4cea-8e56-4ac627003b7a] app/controllers/concerns/localized.rb:16:in `block in set_locale'
web_1        | [58a80b58-eb85-4cea-8e56-4ac627003b7a] app/controllers/concerns/localized.rb:15:in `set_locale'
```

**Comment by weex** [comment]
Not exactly sure about the cause and why it didn't work earlier but after restarting, moving the vars in `.env.production`, single quoting and single-unquoting, I'm now getting an error about it being a test key so it seems ready to try in production with real key tomorrow.
