### ISSUE TITLE
Problem: donations create_package gives key id error

### ISSUE THREAD

**Issue by weex** [magicstone-dev/ecko#365]
Testing create_package and got the following error:

`PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "donation_packages_pkey" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (id)=(1) already exists.`

If I ran the command a few times in succession, the 1 incremented up to a 4 and the package was created. I tried it before creating any packages, then ran `create_packages` which made the three default ones, then ran this four more times. Seems to me some disconnection between the model and the next id that should be made.

```
$ RAILS_ENV=development bin/tootctl donations create_package Blah 25 "blah blah"

DEPRECATION WARNING: add_whitelist is deprecated in favor of add_safelist. It will be removed from the next major release. (called from block (2 levels) in <top (required)> at /vagrant/config/environments/development.rb:84)
Traceback (most recent call last):
	66: from bin/tootctl:8:in `<main>'
	65: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	64: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	63: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	62: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	61: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	60: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	59: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	58: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	57: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	56: from /vagrant/lib/mastodon/donations_cli.rb:72:in `create_package'
	55: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:38:in `create'
	54: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/suppressor.rb:44:in `save'
	53: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `save'
	52: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
	51: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
	50: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
	49: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	48: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	47: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	46: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	45: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	44: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
	43: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
	42: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
	41: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `block in save'
	40: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/validations.rb:47:in `save'
	39: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:474:in `save'
	38: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:126:in `create_or_update'
	37: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `create_or_update'
	36: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
	35: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
	34: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `block in create_or_update'
	33: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:900:in `create_or_update'
	32: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/bullet-6.1.5/lib/bullet/active_record61.rb:6:in `_create_record'
	31: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:108:in `_create_record'
	30: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:461:in `_create_record'
	29: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_create_callbacks'
	28: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
	27: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:461:in `block in _create_record'
	26: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/attribute_methods/dirty.rb:201:in `_create_record'
	25: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/locking/optimistic.rb:79:in `_create_record'
	24: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/counter_cache.rb:166:in `_create_record'
	23: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:929:in `_create_record'
	22: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:375:in `_insert_record'
	21: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
	20: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:171:in `insert'
	19: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `exec_insert'
	18: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `exec_insert'
	17: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:53:in `exec_query'
	16: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
	15: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
	14: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
	13: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	12: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
	11: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	10: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	 9: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	 8: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	 7: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	 6: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
	 5: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
	 4: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	 3: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	 2: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	 1: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
/home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params': ERROR:  duplicate key value violates unique constraint "donation_packages_pkey" (PG::UniqueViolation)
DETAIL:  Key (id)=(1) already exists.
	66: from bin/tootctl:8:in `<main>'
	65: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	64: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	63: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	62: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	61: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	60: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	59: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	58: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	57: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	56: from /vagrant/lib/mastodon/donations_cli.rb:72:in `create_package'
	55: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:38:in `create'
	54: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/suppressor.rb:44:in `save'
	53: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `save'
	52: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
	51: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
	50: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
	49: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	48: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	47: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	46: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	45: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	44: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
	43: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
	42: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
	41: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `block in save'
	40: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/validations.rb:47:in `save'
	39: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:474:in `save'
	38: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:126:in `create_or_update'
	37: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `create_or_update'
	36: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
	35: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
	34: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `block in create_or_update'
	33: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:900:in `create_or_update'
	32: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/bullet-6.1.5/lib/bullet/active_record61.rb:6:in `_create_record'
	31: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:108:in `_create_record'
	30: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:461:in `_create_record'
	29: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_create_callbacks'
	28: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
	27: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:461:in `block in _create_record'
	26: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/attribute_methods/dirty.rb:201:in `_create_record'
	25: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/locking/optimistic.rb:79:in `_create_record'
	24: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/counter_cache.rb:166:in `_create_record'
	23: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:929:in `_create_record'
	22: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:375:in `_insert_record'
	21: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
	20: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:171:in `insert'
	19: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `exec_insert'
	18: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `exec_insert'
	17: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:53:in `exec_query'
	16: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
	15: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
	14: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
	13: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	12: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
	11: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	10: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	 9: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	 8: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	 7: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	 6: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
	 5: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
	 4: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	 3: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	 2: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activesupport-6.1.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	 1: from /home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
/home/vagrant/.rvm/gems/ruby-2.7.4/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params': PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "donation_packages_pkey" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (id)=(1) already exists.
```

**Comment by Mansh05** [comment]
For reference
we could reproduce this when create a package from the console and try to recreate through the tootctl. But now, this issue should not come.
